"""Create models

Revision ID: 8340c4439d7d
Revises: 
Create Date: 2026-01-28 17:21:16.729031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8340c4439d7d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('name', sa.Text(), nullable=False, comment='Наименование'),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата создания записи'),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'parent_id', name='uq_category_name_parent')
    )
    op.create_index('idx_category_parent', 'category', ['parent_id'], unique=False)
    op.create_table('customer',
    sa.Column('name', sa.Text(), nullable=False, comment='Имя'),
    sa.Column('address', sa.Text(), nullable=False, comment='Адрес'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата создания записи'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_customer_name', 'customer', ['name'], unique=False)
    op.create_table('nomenclature',
    sa.Column('name', sa.Text(), nullable=False, comment='Наименование'),
    sa.Column('amount', sa.Integer(), nullable=False, comment='Количество'),
    sa.Column('price', sa.Numeric(), nullable=False, comment='Цена'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата создания записи'),
    sa.CheckConstraint('amount >= 0', name='chk_nomenclature_amount_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_nomenclature_name', 'nomenclature', ['name'], unique=False)
    op.create_index('idx_nomenclature_price', 'nomenclature', ['price'], unique=False)
    op.create_table('order',
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата создания записи'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_order_customer', 'order', ['customer_id'], unique=False)
    op.create_index('idx_order_date', 'order', ['created_at'], unique=False)
    op.create_table('productcategory',
    sa.Column('nomenclature_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['nomenclature_id'], ['nomenclature.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('nomenclature_id', 'category_id'),
    sa.UniqueConstraint('nomenclature_id', 'category_id', name='uq_nomenclature_category')
    )
    op.create_index('idx_pc_category', 'productcategory', ['category_id'], unique=False)
    op.create_index('idx_pc_nomenclature', 'productcategory', ['nomenclature_id'], unique=False)
    op.create_table('orderitem',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('nomenclature_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False, comment='Количество'),
    sa.Column('price', sa.Numeric(), nullable=False, comment='Цена'),
    sa.CheckConstraint('amount > 0', name='chk_order_item_amount_positive'),
    sa.CheckConstraint('price >= 0', name='chk_order_item_price_non_negative'),
    sa.ForeignKeyConstraint(['nomenclature_id'], ['nomenclature.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_id', 'nomenclature_id')
    )
    op.create_index('idx_oi_nomenclature', 'orderitem', ['nomenclature_id'], unique=False)
    op.create_index('idx_oi_order', 'orderitem', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_oi_order', table_name='orderitem')
    op.drop_index('idx_oi_nomenclature', table_name='orderitem')
    op.drop_table('orderitem')
    op.drop_index('idx_pc_nomenclature', table_name='productcategory')
    op.drop_index('idx_pc_category', table_name='productcategory')
    op.drop_table('productcategory')
    op.drop_index('idx_order_date', table_name='order')
    op.drop_index('idx_order_customer', table_name='order')
    op.drop_table('order')
    op.drop_index('idx_nomenclature_price', table_name='nomenclature')
    op.drop_index('idx_nomenclature_name', table_name='nomenclature')
    op.drop_table('nomenclature')
    op.drop_index('idx_customer_name', table_name='customer')
    op.drop_table('customer')
    op.drop_index('idx_category_parent', table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
